grep -HiRr "acessível|adjetivo|singular_feminino"
grep -HiRr "acessível|adjetivo|singular_masculino"
grep -HiRr "ações de comércio justo|locucao_substantiva|singular_masculino"
#grep -HiRr "a comercialização|locucao_adjetiva|singular_feminino"
#grep -HiRr "a comercialização|locucao_substantiva|singular_feminino"
#grep -HiRr "a cooperativas|locucao_adjetiva|plural_feminino"
#grep -HiRr "a cooperativas|locucao_substantiva|plural_feminino"
#grep -HiRr "a economia local|locucao_adjetiva|singular_feminino"
#grep -HiRr "a economia local|locucao_substantiva|singular_feminino"
#grep -HiRr "à economia|locucao_adjetiva|singular_feminino"
#grep -HiRr "à economia|locucao_substantiva|singular_feminino"
#grep -HiRr "a economia solidária|locucao_adjetiva|singular_feminino"
#grep -HiRr "a economia solidária|locucao_substantiva|singular_feminino"
#grep -HiRr "a empreendimentos|locucao_adjetiva|plural_masculino"
#grep -HiRr "a empreendimentos|locucao_substantiva|plural_masculino"
grep -HiRr "agrícola|adjetivo|singular_feminino"
grep -HiRr "agrícola|adjetivo|singular_masculino"
grep -HiRr "agrícolas|adjetivo|plural_feminino"
grep -HiRr "agrícolas|adjetivo|plural_masculino"
#grep -HiRr "a iniciativas solidárias|locucao_adjetiva|plural_feminino"
#grep -HiRr "a iniciativas solidárias|locucao_substantiva|plural_feminino"
grep -HiRr "alvo|adjetivo|plural_feminino"
grep -HiRr "alvo|adjetivo|singular_feminino"
#grep -HiRr "alvo|adjetivo|singular_feminino"
#grep -HiRr "alvo|adjetivo|singular_masculino"
grep -HiRr "anteriores|adjetivo|plural_feminino"
grep -HiRr "anteriores|adjetivo|plural_masculino"
grep -HiRr "ao CADSOL|locucao_adjetiva|singular_masculino"
grep -HiRr "ao CADSOL|locucao_substantiva|singular_masculino"
grep -HiRr "apoiei|verbo|gerundio"
#grep -HiRr "apoiei|verbo|passado"
#grep -HiRr "a programas sociais|locucao_adjetiva|plural_masculino"
#grep -HiRr "a programas sociais|locucao_substantiva|plural_masculino"
grep -HiRr "artesanais|adjetivo|plural_feminino"
grep -HiRr "artesanais|adjetivo|plural_masculino"
grep -HiRr "artesanal|adjetivo|singular_feminino"
grep -HiRr "artesanal|adjetivo|singular_masculino"
#grep -HiRr "atividades de bioconstrução|locucao_substantiva|plural_feminino"
#grep -HiRr "atividades de bioconstrução|locucao_substantiva|singular_feminino"
grep -HiRr "atividades de bioconstrução|locucao_substantiva|singular_feminino"
grep -HiRr "atividades de bioconstrução|substantivo|plural_feminino"
grep -HiRr "atividades de carpintaria|locucao_substantiva|locucao_substantiva_plural_feminina"
#grep -HiRr "atividades de carpintaria|substantivo|plural_feminino"
grep -HiRr "atuantes|adjetivo|plural_feminino"
grep -HiRr "atuantes|adjetivo|plural_masculino"
#grep -HiRr "coletivos|adjetivo|plural_masculino"
#grep -HiRr "coletivos|substantivo|plural_masculino"
#grep -HiRr "com agentes|locucao_adjetiva|plural_masculino"
#grep -HiRr "com agentes|locucao_substantiva|plural_masculino"
grep -HiRr "com foco|adverbio|modo"
#grep -HiRr "com foco|locucao_adverbial|modo"
#grep -HiRr "com foco|locucao_adverbial|modo"
grep -HiRr "com foco|locucao_substantiva|singular_masculino"
grep -HiRr "comissão de decisões|locucao_substantiva|plural_feminino"
#grep -HiRr "comissão de decisões|locucao_substantiva|singular_feminino"
grep -HiRr "competentes|adjetivo|plural_feminino"
grep -HiRr "competentes|adjetivo|plural_masculino"
grep -HiRr "completa|adjetivo|plural_feminino"
grep -HiRr "completa|adjetivo|plural_masculino"
grep -HiRr "completa|adjetivo|plural_masculino"
#grep -HiRr "completa|adjetivo|singular_feminino"
#grep -HiRr "completo|adjetivo|singular_feminino"
#grep -HiRr "completo|adjetivo|singular_masculino"
grep -HiRr "comunitários|adjetivo|plural_feminino"
#grep -HiRr "comunitários|adjetivo|plural_masculino"
grep -HiRr "consistentes|adjetivo|plural_feminino"
grep -HiRr "consistentes|adjetivo|plural_masculino"
#grep -HiRr "cooperativas de reciclagem|locucao_substantiva|plural_feminino"
grep -HiRr "cooperativas de reciclagem|locucao_substantiva|singular_feminino"
grep -HiRr "cooperativas|adjetivo|plural_feminino"
grep -HiRr "cooperativas|locucao_substantiva|plural_feminino"
grep -HiRr "cooperativas|locucao_substantiva|plural_feminino"
grep -HiRr "cooperativas|substantivo|plural_feminino"
grep -HiRr "culturais|adjetivo|plural_feminino"
grep -HiRr "culturais|adjetivo|plural_masculino"
grep -HiRr "cultural|adjetivo|singular_feminino"
grep -HiRr "cultural|adjetivo|singular_masculino"
grep -HiRr "dados culturais|locucao_substantiva|locucao_substantiva_plural_masculina"
grep -HiRr "dados culturais|locucao_substantiva|plural_masculino"
grep -HiRr "dados de comunidades|locucao_substantiva|plural_feminino"
#grep -HiRr "dados de comunidades|locucao_substantiva|plural_masculino"
grep -HiRr "dados demográficos|locucao_substantiva|locucao_substantiva_plural_masculina"
grep -HiRr "dados demográficos|locucao_substantiva|plural_masculino"
grep -HiRr "dados de redes sociais|locucao_substantiva|plural_feminino"
#grep -HiRr "dados de redes sociais|locucao_substantiva|plural_masculino"
grep -HiRr "dados populacionais|locucao_substantiva|locucao_substantiva_plural_masculina"
grep -HiRr "dados populacionais|substantivo|plural_masculino"
grep -HiRr "dados sobre horticultura|locucao_substantiva|locucao_substantiva_singular_feminina"
grep -HiRr "dados sobre horticultura|substantivo|singular_feminino"
#grep -HiRr "de agricultura familiar|locucao_adjetiva|singular_feminino"
grep -HiRr "de agricultura familiar|locucao_substantiva|singular_feminino"
#grep -HiRr "de agroecologia|locucao_adjetiva|singular_feminino"
grep -HiRr "de agroecologia|locucao_substantiva|singular_feminino"
#grep -HiRr "de artesanato|locucao_adjetiva|singular_masculino"
grep -HiRr "de artesanato|locucao_substantiva|singular_feminino"
grep -HiRr "de associações|locucao_adjetiva|plural_feminino"
#grep -HiRr "de associações|locucao_substantiva|plural_feminino"
#grep -HiRr "de atividades|locucao_adjetiva|plural_feminino"
grep -HiRr "de atividades|locucao_substantiva|plural_feminino"
#grep -HiRr "de avaliação|locucao_adjetiva|singular_feminino"
grep -HiRr "de avaliação|locucao_substantiva|singular_feminino"
#grep -HiRr "de bioconstrução|locucao_adjetiva|singular_feminino"
grep -HiRr "de bioconstrução|locucao_substantiva|singular_feminino"
#grep -HiRr "de capacitação|locucao_adjetiva|singular_feminino"
grep -HiRr "de capacitação|locucao_substantiva|singular_feminino"
#grep -HiRr "de conselheiros|locucao_adjetiva|plural_masculino"
grep -HiRr "de conselheiros|locucao_substantiva|plural_masculino"
#grep -HiRr "de conselhos|locucao_adjetiva|plural_masculino"
grep -HiRr "de conselhos|locucao_substantiva|plural_masculino"
#grep -HiRr "de cooperativas|locucao_adjetiva|plural_feminino"
grep -HiRr "de cooperativas|locucao_substantiva|plural_feminino"
#grep -HiRr "de cosméticos naturais|locucao_adjetiva|plural_masculino"
grep -HiRr "de cosméticos naturais|locucao_substantiva|plural_masculino"
#grep -HiRr "de desenvolvimento|locucao_adjetiva|singular_masculino"
grep -HiRr "de desenvolvimento|locucao_substantiva|singular_masculino"
#grep -HiRr "de economia digital|locucao_adjetiva|singular_feminino"
grep -HiRr "de economia digital|locucao_substantiva|singular_feminino"
#grep -HiRr "de economia|locucao_adjetiva|singular_feminino"
grep -HiRr "de economia|locucao_substantiva|singular_feminino"
#grep -HiRr "de economia popular|locucao_adjetiva|singular_feminino"
grep -HiRr "de economia popular|locucao_substantiva|singular_feminino"
#grep -HiRr "de economia solidária|locucao_adjetiva|singular_feminino"
grep -HiRr "de economia solidária|locucao_substantiva|plural_feminino"
#grep -HiRr "de energia renovável|locucao_adjetiva|singular_feminino"
grep -HiRr "de energia renovável|locucao_substantiva|singular_feminino"
#grep -HiRr "de iniciativas|locucao_adjetiva|plural_feminino"
grep -HiRr "de iniciativas|locucao_substantiva|plural_feminino"
#grep -HiRr "de permacultura|locucao_adjetiva|singular_feminino"
grep -HiRr "de permacultura|locucao_substantiva|singular_feminino"
#grep -HiRr "de produtos|locucao_adjetiva|plural_masculino"
grep -HiRr "de produtos|locucao_substantiva|plural_masculino"
#grep -HiRr "de reciclagem|locucao_adjetiva|singular_feminino"
grep -HiRr "de reciclagem|locucao_adjetiva|singular_masculino"
grep -HiRr "de reciclagem|locucao_adjetiva|singular_masculino"
grep -HiRr "de reciclagem|locucao_substantiva|singular_feminino"
#grep -HiRr "de redes comunitárias|locucao_adjetiva|plural_feminino"
grep -HiRr "de redes comunitárias|locucao_substantiva|plural_feminino"
#grep -HiRr "de redes locais|locucao_adjetiva|plural_feminino"
grep -HiRr "de redes locais|locucao_substantiva|plural_feminino"
#grep -HiRr "de redes|locucao_adjetiva|plural_feminino"
grep -HiRr "de redes|locucao_substantiva|plural_feminino"
#grep -HiRr "de seleção|locucao_adjetiva|singular_feminino"
grep -HiRr "de seleção|locucao_substantiva|singular_feminino"
grep -HiRr "detalhada|adjetivo|plural_feminino"
#grep -HiRr "detalhada|adjetivo|singular_feminino"
grep -HiRr "detalhado|adjetivo|singular_feminino"
#grep -HiRr "detalhado|adjetivo|singular_masculino"
grep -HiRr "de turismo comunitário|locucao_adjetiva|singular_feminino"
grep -HiRr "de turismo comunitário|locucao_substantiva|singular_masculino"
grep -HiRr "digitais|adjetivo|plural_feminino"
grep -HiRr "digitais|adjetivo|plural_masculino"
grep -HiRr "digital|adjetivo|singular_feminino"
grep -HiRr "digital|adjetivo|singular_masculino"
grep -HiRr "documento de atividades|locucao_substantiva|singular_feminino"
#grep -HiRr "documento de atividades|locucao_substantiva|singular_masculino"
#grep -HiRr "do território|locucao_adjetiva|singular_masculino"
grep -HiRr "do território|locucao_substantiva|singular_masculino"
grep -HiRr "economia solidária|locucao_adjetiva|singular_feminino"
#grep -HiRr "economia solidária|locucao_substantiva|singular_feminino"
grep -HiRr "econômicos|adjetivo|plural_feminino"
#grep -HiRr "econômicos|adjetivo|plural_masculino"
grep -HiRr "e cooperativas|locucao_adjetiva|plural_feminino"
#grep -HiRr "e cooperativas|locucao_substantiva|plural_feminino"
grep -HiRr "eficaz|adjetivo|singular_feminino"
grep -HiRr "eficaz|adjetivo|singular_masculino"
grep -HiRr "eficazes|adjetivo|plural_feminino"
grep -HiRr "eficazes|adjetivo|plural_masculino"
grep -HiRr "em áreas|locucao_adjetiva|locucao_adjetiva_plural_feminina"
#grep -HiRr "em áreas|locucao_substantiva|plural_feminino"
grep -HiRr "em associações|locucao_adjetiva|plural_feminino"
#grep -HiRr "em associações|locucao_substantiva|plural_feminino"
grep -HiRr "em atividades|locucao_adjetiva|locucao_adjetiva_plural_feminina"
#grep -HiRr "em atividades|locucao_substantiva|plural_feminino"
grep -HiRr "em comunidades|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "em comunidades|locucao_adjetiva|plural_feminino"
grep -HiRr "em comunidades|locucao_adjetiva|plural_feminino"
#grep -HiRr "em comunidades|locucao_substantiva|plural_feminino"
grep -HiRr "em congresso|locucao_adjetiva|singular_masculino"
#grep -HiRr "em congresso|locucao_substantiva|singular_masculino"
grep -HiRr "em conselhos|locucao_adjetiva|plural_masculino"
#grep -HiRr "em conselhos|locucao_substantiva|plural_masculino"
grep -HiRr "em cooperativas|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "em cooperativas|locucao_adjetiva|plural_feminino"
#grep -HiRr "em cooperativas|locucao_adjetiva|plural_feminino"
#grep -HiRr "em cooperativas|locucao_substantiva|plural_feminino"
#grep -HiRr "em economia|locucao_adjetiva|singular_feminino"
#grep -HiRr "em economia|locucao_substantiva|singular_feminino"
grep -HiRr "em encontros|locucao_adjetiva|plural_masculino"
#grep -HiRr "em encontros|locucao_substantiva|plural_masculino"
grep -HiRr "em evento|locucao_adjetiva|singular_masculino"
#grep -HiRr "em evento|locucao_substantiva|singular_masculino"
grep -HiRr "em fóruns|locucao_adjetiva|plural_masculino"
#grep -HiRr "em fóruns|locucao_substantiva|plural_masculino"
grep -HiRr "em iniciativas|locucao_adjetiva|locucao_adjetiva_plural_feminina"
#grep -HiRr "em iniciativas|locucao_substantiva|plural_feminino"
grep -HiRr "em negócios|locucao_adjetiva|plural_masculino"
#grep -HiRr "em negócios|locucao_substantiva|plural_masculino"
grep -HiRr "em ONGs|locucao_adjetiva|plural_feminino"
#grep -HiRr "em ONGs|locucao_substantiva|plural_feminino"
grep -HiRr "em práticas|locucao_adjetiva|plural_feminino"
#grep -HiRr "em práticas|locucao_substantiva|plural_feminino"
grep -HiRr "em projetos|locucao_adjetiva|locucao_adjetiva_plural_masculina"
grep -HiRr "em projetos|locucao_adjetiva|plural_masculino"
grep -HiRr "em projetos|locucao_adjetiva|plural_masculino"
#grep -HiRr "em projetos|locucao_substantiva|plural_masculino"
grep -HiRr "em redes|locucao_adjetiva|plural_feminino"
#grep -HiRr "em redes|locucao_substantiva|plural_feminino"
grep -HiRr "em regiões|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "em regiões|locucao_adjetiva|plural_feminino"
grep -HiRr "em reuniões|locucao_adjetiva|plural_feminino"
#grep -HiRr "em reuniões|locucao_substantiva|plural_feminino"
grep -HiRr "em seminário|locucao_adjetiva|singular_masculino"
#grep -HiRr "em seminário|locucao_substantiva|singular_masculino"
grep -HiRr "em setores|locucao_adjetiva|locucao_adjetiva_plural_masculina"
#grep -HiRr "em setores|locucao_substantiva|plural_masculino"
grep -HiRr "entre cooperativas|locucao_adjetiva|plural_feminino"
#grep -HiRr "entre cooperativas|locucao_substantiva|plural_feminino"
grep -HiRr "e ONGs|locucao_adjetiva|plural_feminino"
#grep -HiRr "e ONGs|locucao_substantiva|plural_feminino"
grep -HiRr "estrutura de eventos|locucao_substantiva|plural_masculino"
#grep -HiRr "estrutura de eventos|locucao_substantiva|singular_feminino"
grep -HiRr "estrutura de vendas|locucao_substantiva|plural_feminino"
#grep -HiRr "estrutura de vendas|locucao_substantiva|singular_feminino"
grep -HiRr "existentes|adjetivo|plural_feminino"
grep -HiRr "existentes|adjetivo|plural_masculino"
grep -HiRr "federais|adjetivo|plural_feminino"
grep -HiRr "federais|adjetivo|plural_masculino"
grep -HiRr "final|adjetivo|singular_feminino"
grep -HiRr "final|adjetivo|singular_masculino"
grep -HiRr "funcional|adjetivo|singular_feminino"
grep -HiRr "funcional|adjetivo|singular_masculino"
grep -HiRr "governamentais|adjetivo|plural_feminino"
grep -HiRr "governamentais|adjetivo|plural_masculino"
#grep -HiRr "grupos comunitários|locucao_substantiva|plural_masculino"
grep -HiRr "grupos comunitários|substantivo|plural_masculino"
#grep -HiRr "grupos de apoio|locucao_substantiva|plural_masculino"
grep -HiRr "grupos de apoio|substantivo|plural_masculino"
grep -HiRr "importantes|adjetivo|plural_feminino"
grep -HiRr "importantes|adjetivo|plural_masculino"
grep -HiRr "infraestrutura de eventos|locucao_substantiva|plural_masculino"
#grep -HiRr "infraestrutura de eventos|locucao_substantiva|singular_feminino"
grep -HiRr "infraestrutura de feiras|locucao_substantiva|plural_feminino"
#grep -HiRr "infraestrutura de feiras|locucao_substantiva|singular_feminino"
grep -HiRr "inicial|adjetivo|singular_feminino"
grep -HiRr "inicial|adjetivo|singular_masculino"
#grep -HiRr "iniciativas de ecoturismo|locucao_substantiva|plural_feminino"
grep -HiRr "iniciativas de ecoturismo|locucao_substantiva|singular_feminino"
#grep -HiRr "iniciativas de marcenaria|locucao_substantiva|plural_feminino"
grep -HiRr "iniciativas de marcenaria|locucao_substantiva|singular_feminino"
grep -HiRr "iniciativas|locucao_substantiva|plural_feminino"
#grep -HiRr "iniciativas|substantivo|plural_feminino"
grep -HiRr "integral|adjetivo|singular_feminino"
grep -HiRr "integral|adjetivo|singular_masculino"
grep -HiRr "levantados|adjetivo|plural_feminino"
#grep -HiRr "levantados|adjetivo|plural_masculino"
#grep -HiRr "líderes comunitários|locucao_substantiva|plural_masculino"
grep -HiRr "líderes comunitários|substantivo|plural_masculino"
grep -HiRr "locais|adjetivo|plural_feminino"
grep -HiRr "locais|adjetivo|plural_masculino"
grep -HiRr "locais|adjetivo|plural_masculino"
grep -HiRr "locais|adjetivo|singular_feminino"
grep -HiRr "local|adjetivo|singular_feminino"
grep -HiRr "local|adjetivo|singular_masculino"
grep -HiRr "logística|adjetivo|singular_feminino"
grep -HiRr "logística|substantivo|singular_feminino"
grep -HiRr "mensal|adjetivo|singular_feminino"
grep -HiRr "mensal|adjetivo|singular_masculino"
grep -HiRr "mesa de conselhos|locucao_substantiva|plural_feminino"
#grep -HiRr "mesa de conselhos|locucao_substantiva|singular_feminino"
grep -HiRr "motivacional|adjetivo|singular_feminino"
grep -HiRr "motivacional|adjetivo|singular_masculino"
grep -HiRr "na apicultura|locucao_adjetiva|locucao_adjetiva_singular_feminina"
grep -HiRr "na apicultura|locucao_adjetiva|singular_feminino"
grep -HiRr "na área|locucao_adjetiva|locucao_adjetiva_singular_feminina"
#grep -HiRr "na área|locucao_substantiva|singular_feminino"
grep -HiRr "na autogestão|locucao_adjetiva|singular_feminino"
#grep -HiRr "na autogestão|locucao_substantiva|singular_feminino"
grep -HiRr "nacionais|adjetivo|plural_feminino"
grep -HiRr "nacionais|adjetivo|plural_masculino"
grep -HiRr "nacional|adjetivo|singular_feminino"
grep -HiRr "nacional|adjetivo|singular_masculino"
grep -HiRr "na comunidade|locucao_adjetiva|locucao_adjetiva_singular_feminina"
grep -HiRr "na comunidade|locucao_adjetiva|singular_feminino"
grep -HiRr "na economia|locucao_adjetiva|locucao_adjetiva_singular_feminina"
grep -HiRr "na economia|locucao_adjetiva|singular_feminino"
grep -HiRr "na economia solidária|locucao_adjetiva|locucao_adjetiva_singular_feminina"
grep -HiRr "na economia solidária|locucao_adjetiva|singular_feminino"
grep -HiRr "na elaboração|locucao_adjetiva|singular_feminino"
grep -HiRr "na elaboração|locucao_substantiva|singular_feminino"
grep -HiRr "na produção|locucao_adjetiva|locucao_adjetiva_singular_feminina"
grep -HiRr "na produção|locucao_substantiva|singular_feminino"
grep -HiRr "na região|locucao_adjetiva|locucao_adjetiva_singular_feminina"
grep -HiRr "na região|locucao_adjetiva|singular_feminino"
grep -HiRr "nas áreas|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "nas áreas|locucao_substantiva|plural_feminino"
grep -HiRr "nas comunidades|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "nas comunidades|locucao_adjetiva|plural_feminino"
grep -HiRr "nas comunidades|locucao_adjetiva|plural_feminino"
grep -HiRr "nas comunidades|locucao_substantiva|plural_feminino"
grep -HiRr "nas cooperativas|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "nas cooperativas|locucao_adjetiva|plural_feminino"
grep -HiRr "nas regiões|locucao_adjetiva|locucao_adjetiva_plural_feminina"
grep -HiRr "nas regiões|locucao_substantiva|plural_feminino"
grep -HiRr "naturais|adjetivo|plural_feminino"
grep -HiRr "naturais|adjetivo|plural_masculino"
grep -HiRr "no CADSOL|locucao_adjetiva|singular_masculino"
grep -HiRr "no CADSOL|locucao_substantiva|singular_masculino"
grep -HiRr "no processo|locucao_adjetiva|singular_masculino"
grep -HiRr "no processo|locucao_substantiva|singular_masculino"
grep -HiRr "no setor|locucao_adjetiva|locucao_adjetiva_singular_masculina"
grep -HiRr "no setor|locucao_substantiva|singular_masculino"
grep -HiRr "no território|locucao_adjetiva|locucao_adjetiva_singular_masculina"
grep -HiRr "no território|locucao_adjetiva|singular_masculino"
grep -HiRr "no território|locucao_adjetiva|singular_masculino"
grep -HiRr "no território|locucao_substantiva|singular_masculino"
grep -HiRr "oficial|adjetivo|singular_feminino"
grep -HiRr "oficial|adjetivo|singular_masculino"
grep -HiRr "online|adjetivo|singular_feminino"
grep -HiRr "online|adjetivo|singular_masculino"
grep -HiRr "organizada|adjetivo|plural_feminino"
grep -HiRr "organizada|adjetivo|singular_feminino"
grep -HiRr "para ações|locucao_adjetiva|plural_feminino"
grep -HiRr "para ações|locucao_substantiva|plural_feminino"
grep -HiRr "para agricultura familiar|locucao_adjetiva|singular_feminino"
grep -HiRr "para agricultura familiar|locucao_substantiva|singular_feminino"
grep -HiRr "para análise|locucao_adjetiva|singular_feminino"
grep -HiRr "para análise|locucao_substantiva|singular_feminino"
grep -HiRr "para apoiar|locucao_adjetiva|singular_masculino"
grep -HiRr "para apoiar|locucao_verbal|infinitivo"
grep -HiRr "para artesãos|locucao_adjetiva|plural_masculino"
grep -HiRr "para artesãos|locucao_substantiva|plural_masculino"
grep -HiRr "para coletivos locais|locucao_adjetiva|plural_masculino"
grep -HiRr "para coletivos locais|locucao_substantiva|plural_masculino"
grep -HiRr "para coletivos|locucao_adjetiva|plural_masculino"
grep -HiRr "para coletivos|locucao_substantiva|plural_masculino"
grep -HiRr "para cooperativas|locucao_adjetiva|plural_feminino"
grep -HiRr "para cooperativas|locucao_substantiva|plural_feminino"
grep -HiRr "para desenvolvimento|locucao_adjetiva|singular_masculino"
grep -HiRr "para desenvolvimento|locucao_substantiva|singular_masculino"
grep -HiRr "para documentação|locucao_adjetiva|singular_feminino"
grep -HiRr "para documentação|locucao_substantiva|singular_feminino"
grep -HiRr "para economia|locucao_adjetiva|singular_feminino"
grep -HiRr "para economia|locucao_substantiva|singular_feminino"
grep -HiRr "para economia solidária|adjetivo|singular_feminino"
grep -HiRr "para economia solidária|locucao_adjetiva|singular_feminino"
grep -HiRr "para empreendimentos locais|locucao_adjetiva|plural_masculino"
grep -HiRr "para empreendimentos locais|locucao_substantiva|plural_masculino"
grep -HiRr "para empreendimentos|locucao_adjetiva|plural_masculino"
grep -HiRr "para empreendimentos|locucao_substantiva|plural_masculino"
grep -HiRr "para financiamento|locucao_adjetiva|singular_masculino"
grep -HiRr "para financiamento|locucao_substantiva|singular_masculino"
grep -HiRr "para formação|locucao_adjetiva|singular_feminino"
grep -HiRr "para formação|locucao_substantiva|singular_feminino"
grep -HiRr "para fortalecer|locucao_adjetiva|singular_masculino"
grep -HiRr "para fortalecer|locucao_verbal|infinitivo"
grep -HiRr "para gestão|locucao_adjetiva|singular_feminino"
grep -HiRr "para gestão|locucao_substantiva|singular_feminino"
grep -HiRr "para grupos|locucao_adjetiva|plural_masculino"
grep -HiRr "para grupos|locucao_substantiva|plural_masculino"
grep -HiRr "para incentivar|locucao_adjetiva|singular_masculino"
grep -HiRr "para incentivar|locucao_verbal|infinitivo"
grep -HiRr "para inclusão|locucao_adjetiva|singular_feminino"
grep -HiRr "para inclusão|locucao_substantiva|singular_feminino"
grep -HiRr "para iniciativas locais|locucao_adjetiva|plural_feminino"
grep -HiRr "para iniciativas locais|locucao_substantiva|plural_feminino"
grep -HiRr "para iniciativas|locucao_adjetiva|plural_feminino"
grep -HiRr "para iniciativas|locucao_substantiva|plural_feminino"
grep -HiRr "para iniciativas solidárias|locucao_adjetiva|plural_feminino"
grep -HiRr "para iniciativas solidárias|locucao_substantiva|plural_feminino"
grep -HiRr "para monitoramento|locucao_adjetiva|singular_masculino"
grep -HiRr "para monitoramento|locucao_substantiva|singular_masculino"
grep -HiRr "para negócios|locucao_adjetiva|plural_masculino"
grep -HiRr "para negócios|locucao_substantiva|plural_masculino"
grep -HiRr "para o CADSOL|locucao_adjetiva|singular_masculino"
grep -HiRr "para o CADSOL|locucao_substantiva|singular_masculino"
grep -HiRr "para o território|locucao_adjetiva|singular_masculino"
grep -HiRr "para o território|locucao_substantiva|singular_masculino"
grep -HiRr "para práticas|locucao_adjetiva|plural_feminino"
grep -HiRr "para práticas|locucao_substantiva|plural_feminino"
grep -HiRr "para processos|locucao_adjetiva|plural_masculino"
grep -HiRr "para processos|locucao_substantiva|plural_masculino"
grep -HiRr "para produtos reciclados|locucao_adjetiva|plural_masculino"
grep -HiRr "para produtos reciclados|locucao_substantiva|plural_masculino"
grep -HiRr "para redes locais|locucao_adjetiva|plural_feminino"
grep -HiRr "para redes locais|locucao_substantiva|plural_feminino"
grep -HiRr "para redes|locucao_adjetiva|plural_feminino"
grep -HiRr "para redes|locucao_substantiva|plural_feminino"
grep -HiRr "para redes solidárias|locucao_adjetiva|plural_feminino"
grep -HiRr "para redes solidárias|locucao_substantiva|plural_feminino"
grep -HiRr "para registro|locucao_adjetiva|singular_masculino"
grep -HiRr "para registro|locucao_substantiva|singular_masculino"
grep -HiRr "para trabalhadores|locucao_adjetiva|plural_masculino"
grep -HiRr "para trabalhadores|locucao_substantiva|plural_masculino"
grep -HiRr "pertinentes|adjetivo|plural_feminino"
grep -HiRr "pertinentes|adjetivo|plural_masculino"
grep -HiRr "popular|adjetivo|singular_feminino"
grep -HiRr "popular|adjetivo|singular_masculino"
grep -HiRr "populares|adjetivo|plural_feminino"
grep -HiRr "populares|adjetivo|plural_masculino"
grep -HiRr "preparação de edital|locucao_substantiva|singular_feminino"
grep -HiRr "preparação de edital|locucao_substantiva|singular_masculino"
grep -HiRr "presentes|adjetivo|plural_feminino"
grep -HiRr "presentes|adjetivo|plural_masculino"
grep -HiRr "processo de inscrição|locucao_substantiva|singular_feminino"
grep -HiRr "processo de inscrição|locucao_substantiva|singular_masculino"
grep -HiRr "produção agrícola|locucao_substantiva|singular_feminino"
grep -HiRr "produção agrícola|substantivo|singular_feminino"
grep -HiRr "recursos comunitários|locucao_substantiva|locucao_substantiva_plural_masculina"
grep -HiRr "recursos comunitários|locucao_substantiva|plural_masculino"
grep -HiRr "recursos culturais|locucao_substantiva|locucao_substantiva_plural_masculina"
grep -HiRr "recursos culturais|substantivo|plural_masculino"
grep -HiRr "recursos produtivos|locucao_substantiva|locucao_substantiva_plural_masculina"
grep -HiRr "recursos produtivos|locucao_substantiva|plural_masculino"
grep -HiRr "redes de apoio comunitário|locucao_substantiva|plural_feminino"
grep -HiRr "redes de apoio comunitário|substantivo|plural_feminino"
grep -HiRr "redes de apoio|locucao_substantiva|plural_feminino"
grep -HiRr "redes de apoio|substantivo|plural_feminino"
grep -HiRr "redes de colaboração|locucao_substantiva|plural_feminino"
grep -HiRr "redes de colaboração|substantivo|plural_feminino"
grep -HiRr "redes de suporte|locucao_substantiva|plural_feminino"
grep -HiRr "redes de suporte|substantivo|plural_feminino"
grep -HiRr "regionais|adjetivo|plural_feminino"
grep -HiRr "regionais|adjetivo|plural_masculino"
grep -HiRr "regionais|adjetivo|plural_masculino"
grep -HiRr "regionais|adjetivo|singular_feminino"
grep -HiRr "regional|adjetivo|singular_feminino"
grep -HiRr "regional|adjetivo|singular_masculino"
grep -HiRr "regulares|adjetivo|plural_feminino"
grep -HiRr "regulares|adjetivo|plural_masculino"
grep -HiRr "relevantes|adjetivo|plural_feminino"
grep -HiRr "relevantes|adjetivo|plural_masculino"
grep -HiRr "responsáveis|adjetivo|plural_feminino"
grep -HiRr "responsáveis|adjetivo|plural_masculino"
grep -HiRr "rural|adjetivo|singular_feminino"
grep -HiRr "rural|adjetivo|singular_masculino"
grep -HiRr "semanal|adjetivo|singular_feminino"
grep -HiRr "semanal|adjetivo|singular_masculino"
grep -HiRr "seminário de finanças|locucao_substantiva|plural_feminino"
grep -HiRr "seminário de finanças|locucao_substantiva|singular_feminino"
grep -HiRr "significativos|adjetivo|plural_feminino"
grep -HiRr "significativos|adjetivo|plural_masculino"
grep -HiRr "sob estudo|adjetivo|singular_masculino"
grep -HiRr "sob estudo|locucao_adjetiva|singular_feminino"
grep -HiRr "sob estudo|locucao_adjetiva|singular_feminino"
grep -HiRr "sob estudo|locucao_adjetiva|singular_masculino"
grep -HiRr "sob foco|locucao_adjetiva|singular_feminino"
grep -HiRr "sob foco|locucao_adjetiva|singular_masculino"
grep -HiRr "sobre economia|locucao_adjetiva|singular_feminino"
grep -HiRr "sobre economia|locucao_substantiva|singular_feminino"
grep -HiRr "sobre práticas|locucao_adjetiva|plural_feminino"
grep -HiRr "sobre práticas|locucao_substantiva|plural_feminino"
grep -HiRr "sustentáveis|adjetivo|plural_feminino"
grep -HiRr "sustentáveis|adjetivo|plural_masculino"
grep -HiRr "sustentável|adjetivo|singular_feminino"
grep -HiRr "sustentável|adjetivo|singular_masculino"
grep -HiRr "territoriais|adjetivo|plural_feminino"
grep -HiRr "territoriais|adjetivo|plural_masculino"
grep -HiRr "urbanos|adjetivo|plural_feminino"
grep -HiRr "urbanos|adjetivo|plural_masculino"
grep -HiRr "virtual|adjetivo|singular_feminino"
grep -HiRr "virtual|adjetivo|singular_masculino"
grep -HiRr "voltadas para|locucao_adjetiva|infinitivo"
grep -HiRr "voltadas para|locucao_verbal|infinitivo"
