-- (Re)criação da tabela regioes_atuacao
DROP TABLE IF EXISTS regioes_atuacao;
CREATE TABLE regioes_atuacao (
  id_chave_regiao_atuacao INT AUTO_INCREMENT PRIMARY KEY,
  nome_regiao_atuacao VARCHAR(255) UNIQUE
) ENGINE=InnoDB;

-- Inserts únicos em regioes_atuacao
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('São Paulo - Leste 2');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('DF');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('Sumaré SP');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('Campinas SP');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('São Paulo - ABC');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('São Paulo - Leste 1');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('São Paulo - A confirmar');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('São Paulo - Butantã');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('São Paulo - Zona Norte');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('AM');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('BA');
INSERT INTO regioes_atuacao (nome_regiao_atuacao) VALUES ('CE');

-- Inserts em tipos_vinculos (para perfis do CSV)
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Diretoria SENAES', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('TI', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Testador', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Avaliador frases', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Presidência', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Coordenação', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Bolsista com Ação Territorial', 'Inserido automaticamente a partir do CSV');
INSERT IGNORE INTO tipos_vinculos (nome_tipo_vinculo, descricao) VALUES ('Bolsista para a Coordenação Estadual', 'Inserido automaticamente a partir do CSV');

-- Alterações na tabela pessoas para incluir FKs
ALTER TABLE pessoas
  ADD COLUMN id_tipo_vinculo INT,
  ADD COLUMN id_regiao_atuacao INT,
  ADD CONSTRAINT fk_tipo_vinculo FOREIGN KEY (id_tipo_vinculo) REFERENCES tipos_vinculos(id_chave_tipo_vinculo),
  ADD CONSTRAINT fk_regiao_atuacao FOREIGN KEY (id_regiao_atuacao) REFERENCES regioes_atuacao(id_chave_regiao_atuacao);

-- Inserts na tabela pessoas
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Sérgio Godoy', 'sergio.godoy@trabalho.gov.br', '(61)', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Diretoria SENAES'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Leste 2'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Victor Pellegrini Mammana', 'vpmammana@gmail.com', '(19) 981431010', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'TI'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Wagner Tome', 'wagts2006@gmail.com', '(19) 981431010', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'TI'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'Sumaré SP'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Testador1', 'testador.1@gmail.com', '61', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Testador'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Testador2', 'testador.2@gmail.com', '61', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Testador'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Testador3', 'testador.3@gmail.com', '61', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Testador'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Testador4', 'testador.4@gmail.com', '61', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Testador'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Testador5', 'testador.5@gmail.com', '61', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Testador'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Luisa Alves', 'luisa.alves@gmail.com', '61', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Avaliador frases'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Rafael Monico', 'rafamonico13@gmail.com', '11', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Avaliador frases'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'DF'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Pedro Tourinho', 'pedro.tourinho@fundacentro.gov.br', '(19)', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Presidência'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'Campinas SP'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Eberval Castro', 'eberval.castro@fundacentro.gov.br', '(19)', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Coordenação'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'Campinas SP'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Aline Mary Vinci da Silva', 'alinemarypt13@gmail.com', '(11) 9 4758.0905', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Leste 2'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Elenilson de Melo Silva', 'nilsonlesbc@gmail.com', '(11) 96289. 8316', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - ABC'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Ivonete Aparecida dos Santos', 'Ivonetedagat@gmail.com', '(11) 97725.6995', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Leste 1'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('José Moisés Vilas Boas Neto', 'oxifotofilme@gmail.com', '(11) 95131.1219', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Leste 1'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Julia Leite Cassa', 'juliacassa2@gmail.com', '(19) 988314224', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - A confirmar'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Julia Pedote Lourenção', 'Julia.lourencao@alumni.usp.br', '(11) 9 9102.3534', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Butantã'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Luciana Mena Bellato', 'llucianamena@gmail.com', '(11) 9 4845.3870', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - ABC'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Marcia Elena Nascimento Fachini', 'marcia.efachini@gmail.com', '(11) 9 6528.7671', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - ABC'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Michel Conz Fukuda Pereira Alves dos Santos', 'michel.fukuda@gmail.com', '(19) 9 8932.7645', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Zona Norte'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Odair Miguel Chaves', 'odairmiguel@hotmail.com', '(12) 9 9662.4991', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Leste 2'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Ricardo Goes Spoladore', 'ritch.spoladore@gmail.com', '(11) 9 1318.4869', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Leste 1'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Rute Ferreira Menezes', 'ruteeferreiramenezes@gmail.com', '(11) 9 7014.2980', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - ABC'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Walter Cruz de Oliveira', 'Waltercruzoliveira@hotmail.com', '', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista com Ação Territorial'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'São Paulo - Zona Norte'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Maria Cristina Ribeiro De Oliveira', 'mariac.oliveira@trabalho.gov.br', '(92) 99223-5076', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista para a Coordenação Estadual'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'AM'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Terezinha Silva Barbosa Rosenhaim', 'terezinha.rosenhaim@trabalho.gov.br', '(83) 98906-1298', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista para a Coordenação Estadual'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'AM'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Josélia Cerqueira Paixão', 'Joselia.Paixao@trabalho.gov.br', '(71) 98258-9017', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista para a Coordenação Estadual'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'BA'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Magda De Sousa Almeida', 'magda.almeida@trabalho.gov.br', '(71) 98156-5557', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista para a Coordenação Estadual'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'BA'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Ana Celia Vital Batista', 'anac.batista@trabalho.gov.bR', '(85) 99838-2133', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista para a Coordenação Estadual'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'CE'));
INSERT INTO pessoas (nome_pessoa, email, telefone, id_tipo_vinculo, id_regiao_atuacao) VALUES ('Tamy Barbosa De Sousa', 'tamy.sousa@trabalho.gov.br', '(85) 98627-3795', (SELECT id_chave_tipo_vinculo FROM tipos_vinculos WHERE nome_tipo_vinculo = 'Bolsista para a Coordenação Estadual'), (SELECT id_chave_regiao_atuacao FROM regioes_atuacao WHERE nome_regiao_atuacao = 'CE'));

-- Inserts na tabela usuarios
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('sergio.godoy', '', 'c3896e7fe7f6f5355d615492b1e3a8f17fe5ea932fdfc869ad4c4ffc02e735ab', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'sergio.godoy@trabalho.gov.br'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('vpmammana', '', 'dea1844447c3ec37ca4b7a8c5b3b1bb0d8a64066d79aad4f7722f1f1908d2c92', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'vpmammana@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('wagts2006', '', 'ada417fae7dc8eb8fb3df95e5be634253e83d469b4cdf5293c49e1d9031bb471', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'wagts2006@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('testador.1', '', '1fdf55bdf742a73994abe4fa36cc531a926f228e391f4539630af2ed668e8a21', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'testador.1@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('testador.2', '', 'ae4e12d7f175abf7bf8701df0a171699fa59b8dfa79b552db1d956282f21b993', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'testador.2@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('testador.3', '', 'f16191b4932a92983f94cba3350aee58fbb4dbc94a0a86295970aa893532416a', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'testador.3@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('testador.4', '', '5b591c8e6deb0bd88ea986d70dc3274438211a2c45a5e7a67b8ec9e7862cae6e', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'testador.4@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('testador.5', '', '517c375149392947f3cae3fcef7d4d7d5f1c0ac1a75c53c4a93dd531962e44d9', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'testador.5@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('luisa.alves', '', 'b3c7c4062de06632dbdd29ccabee4379d909b4f520ba0049b687c78880bf4de6', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'luisa.alves@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('rafamonico13', '', 'e559df06527a3de2a5fef92d693704cc0bcc57b268c88121c7fce0b784f34aba', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'rafamonico13@gmail.com'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('pedro.tourinho', '', '64abcc5983f2c6c853e37c2d695041b0383def65ba81c75e4ff9cad70f056b6f', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'pedro.tourinho@fundacentro.gov.br'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('eberval.castro', '', 'f0bfe6c0e5476b3fc091f92207f80059c14ff8e0656e59372698b880d4a7510b', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'eberval.castro@fundacentro.gov.br'), 'sim');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('alinemarypt13', '', 'b0fab3dcea55fe66773a8d3efcf9837d3e3b0f5a259406af6eae5efd45eb35e9', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'alinemarypt13@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('nilsonlesbc', '', '2a13e1ed94d6173ec7d38db13d21259e2cc11a8d37f1741244960dffeb82f01e', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'nilsonlesbc@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('Ivonetedagat', '', '4d3e058a02b8da366220ec5fe00b9ebce22759328779214d7477a82b1d63a327', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'Ivonetedagat@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('oxifotofilme', '', '197867ee6cc8f23431aa38dae5c04061527c2afd03bfc7b7ba67e7b54ab88913', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'oxifotofilme@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('juliacassa2', '', '01adfdacd04e532176a48b718b5afdaf1676b39d77389f92db7d03cb73025d34', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'juliacassa2@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('Julia.lourencao', '', '89d508aa28d94bd61e0a89f0ed634584bcb93c40fdf1d0457d070776d1a461c0', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'Julia.lourencao@alumni.usp.br'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('llucianamena', '', '95d510fb94f98b0845e8847a836bce1b475774a8dde56744eb52b796ec6fb5e4', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'llucianamena@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('marcia.efachini', '', '9cfa59ddcb918d983b3b1659059191c06b16aa5e5a05797d56b2cc3e85bd746e', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'marcia.efachini@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('michel.fukuda', '', '646e6b95046e3f155391590ed2611d4dc29b57bdebd6b941e8a1dd16d88ea7bb', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'michel.fukuda@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('odairmiguel', '', '97f3ed21209b68137f9d5a04aad5230aa1de4256a96b403f7aeb2beb8babf71b', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'odairmiguel@hotmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('ritch.spoladore', '', 'b29491803d940b069160abfbb5f352c118d6733db508c4e31c90d5e9dfe8b4ac', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'ritch.spoladore@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('ruteeferreiramenezes', '', '93e2227570e8f26866677139c673abf4fc58877f6646eb84778e6edfd9812a5f', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'ruteeferreiramenezes@gmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('Waltercruzoliveira', '', 'fe8302673f94ab11d3e18e8e1cfa308f8b9fcd48ac29ee319d98ecd1305289f8', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'Waltercruzoliveira@hotmail.com'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('mariac.oliveira', '', '1189c139db978511db0f6a7b24ebc0b3679f37208f443e012bccd725ef761899', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'mariac.oliveira@trabalho.gov.br'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('terezinha.rosenhaim', '', '2a9d670b8e2893a13d0f9db84bcb71b51bd472e01c1e3ba65f4f93c5fb55342a', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'terezinha.rosenhaim@trabalho.gov.br'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('Joselia.Paixao', '', '8792d24f66461a32601670d5524fe425492edf1ba9217c2e2259d17c1e6b1c90', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'Joselia.Paixao@trabalho.gov.br'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('magda.almeida', '', 'd53cb0c19ef11dbef2c4a35f11c85025bff79c802e8f42fb7e1f8fab2097bde1', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'magda.almeida@trabalho.gov.br'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('anac.batista', '', '751aee014536e21f0f2e961ed797e3c3f4f637f336c0eb8964d3a35ec00cf19e', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'anac.batista@trabalho.gov.bR'), 'nao');
INSERT INTO usuarios (nome_usuario, senha, hash, data_inicio_cadastro, id_pessoa, pode_msg) VALUES ('tamy.sousa', '', 'a52d9480883f503609450aba406aedc0cf9d49daffc1548929c0a92ea4ac6007', CURDATE(), (SELECT id_chave_pessoa FROM pessoas WHERE email = 'tamy.sousa@trabalho.gov.br'), 'nao');
